---
client:
  hosts:
    - devopslearning.xyz
  port: 9200
  url_prefix:
  use_ssl: True
  certificate: /etc/ssl/certs/ca-certificates.crt
  client_cert:
  client_key:
  aws_key:
  aws_secret_key:
  aws_region:
  ssl_no_validate: False
  http_auth: "{{ elk_username }}:{{ elk_password }}" 
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
