actions:
  1:
    action: delete_indices
    description: >-
            Delete local indicies that are older then 30 days
    options:
      ignore_empty_list: True
      disable_action: False
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 30
